### PR TITLE
Index 0 on empty list

### LINKED ISSUE #59: adding first item to the list returning an undefined index
hey guys

i found a bug in can-query-logic with realtimeRestModel.
if a have an empty list and i will add the first item to it, by saving it, i hit this line: 
https://github.com/canjs/can-query-logic/blob/master/src/helpers.js#L105
but with an empty list the first index should be `0` and not `undefined`. so i wondering why you checked for `!items.length` because `items.length` with `0` is `true`.

Example:
https://codepen.io/pYr0x/pen/mdwOQyo

### PR DESCRIPTION
**Pull request by pYr0x**
close #59

### CODE REVIEW

**Comment by cherifGsoul** [comment]
Hi @pYr0x , thank you for the PR.
I'm wondering why `getIndex` should return `0` if the items list is empty?
isn't returning index 0 means there's at least 1 item in the list?

**Comment by pYr0x** [comment]
`getIndex` is used to find the index in the list, where the item should be placed into.
https://github.com/canjs/can-connect/blob/86fa195baded0cec1402b1c6ebe0dcecd9e3f5e6/real-time/real-time.js#L486
if the list is empty the item should be placed at the `0` position.

**Comment by pYr0x** [comment]
any change to get this fixed soon?

**Comment by marshallswain** [comment]
Released as `can-query-logic@1.2.4`.  @pYr0x

**Pull request merged**
